from typing import Protocol
from vortenix_newsletter.domain.models import ResearchContext,ResearchFinding,ResearchPlan,SourceDocument,VerticalResearchResult
class ResearchVertical(Protocol):
    """Topic-independent contract consumed by research workflows."""

    @property
    def vertical_id(self)->str: ...
    def build_research_plan(self,context: ResearchContext)->ResearchPlan: ...
    async def analyse(self,documents: list[SourceDocument])->VerticalResearchResult: ...
    def rank_findings(self,findings: list[ResearchFinding])->list[ResearchFinding]: ...
